M48
; DRILL file {KiCad (6.0.6)} date Thu Oct 20 14:17:53 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-20T14:17:53+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1398
%
G90
G05
T1
X7.1813Y-5.8266
X7.4089Y-5.8266
T2
X5.815Y-5.1969
T3
X5.815Y-4.2126
T4
X7.3272Y-2.9083
T5
X4.824Y-2.9083
X6.9972Y-2.2886
T0
M30
